- docs/forms-interaction-process.md
- docs/navigation-process.md
- docs/pending-queue-process.md
- src/main.js
- src/model-application.js
- src/template-form-controls.mustache
- src/view-form-controls.js
- src/view-interaction.js
- tests/.eslintrc
- tests/loader.js
- tests/unit/model-application.js
- tests/unit/view-interaction.js
This PR:
- hides the "save" draft button if there is no storage
- prevents initialisation of the pending queue if there is no storage
- causes the "submit" button to skip the pending queue if there is no storage
Additionally:
- the post-submission pop-up now wraps content in a `<p>` if it is not HTML
- the `BMP.BIC.view.popup(message)` method cleans up after itself to avoid duplicate pop-ups
> BIC-147: fix forms submission when storage is not available

- src/backbone-fix.js
- src/model-application.js
- src/promise-blinkgap.js
- src/promise-indexeddb.js
- tests/loader.js
- tests/unit/promise-blinkgap.js
BIC-154:
- wire up `Backbone.sync` so that it's easier to tell when it's been called improperly
- don't try to use persistence features with the model at `BMP.BIC` because it isn't a persistent model anymore
BIC-175:
- fix the timed promise code so that `resolve()` isn't hit twice
- convert a `jQuery.Deferred` to a real `Promise` to solve chaining problems (caused BlinkGap detection to kill everything during initialisation)
> BIC-175 # fix BlinkGap detection so it doesn't kill everything

- src/bic/model-application.js
- src/bic/template/form/controls.mustache
- src/bic/view-form-action.js
- src/bic/view-form-controls.js
- tests/loader.js
- tests/unit/view-form-action.js
- tests/unit/view-form-controls.js
- BMP.BIC.views.FormControls: location override default form control view
- view-form-action: added prepareSubView method that checks to see above setting to decide which view to use
- view-form-controls: added last/first page functions
- moved template to folder + added template part for first/last pagination buttons
- added tests to confirm next/previous/first/last button functions work correctly
- added prepareSubView works as expected
> BIC-173 # improve Forms pagination controls, make extensible

- Gruntfile.js
- package.json
- src/bic/view-interaction.js
- src/buildFiles/files/index.mustache
- tests/loader.js
We already have a initialisation watchdog, but that is created by the BIC and requires the BIC.
This PR introduces an earlier Require.js watchdog that functions even when the BIC is broken. It requires BMP v2.25.0 and up, due to implementation in the initial HTML template.
Sequence:
1. if missing basic `Array` methods that the watchdog uses (e.g. in IE8) then redirect to http://outdatedbrowser.com/
2. if Require.js itself failed to load, then reload
3. if Require.js fails to load a core dependency (e.g. jQuery, jQuery Mobile, Backbone, PouchDB), then reload
In my testing in Chrome Dev. Tools simulating a Regular 2G connection, this recovers from the typical module timeouts that occurs as expected. Note that caching must be enabled for recovery, otherwise we get into a timeout loop.
I did …
> BIC-161 # reload during init if core deps fail

- src/bic/promise-blinkgap.js
This was killing the native iOS and Android apps.
> BIC-181 # load jQuery _before_ `BlinkGap.whenReady()`

- src/bic/view-form-controls.js
- instead of page create, use 'create' on element, which will only enhance child elements
> BIC-179 # turning Forms pages over-enhances elements

- src/bic/view-interaction.js
Capital 'M' to lower case 'm' makes case sensitive things happy.
> BIC-164 - Fixed spelling mistake preventing kml maps from working

- package.json
- src/bic.js
- src/bic/form-expressions.js
- src/bic/model-application.js
- src/bic/router.js
- all modules that use `Promise` now explicitly `require('feature!promises');`
- the main BIC module defines `window.Promise` if it is undefined
- skip a few persistent steps during initialisation if we don't have persistent storage
> BIC-187 # fix post-restructure issues breaking Android 4.3, iOS 7, IE 10-11

- .eslintignore
- src/bic/view-form-controls.js
- tests/unit/view-form-controls.js
- first, last, next, previous: just changes the page
-- leaves everything else on page change event
-- once page change happens and page injected triggers
- bind event once, so every time render gets called, he removes the event handler and adds it back again
- so api's and buttons will use same behaviour
- removed checks in test for render function calls
> BIC-180 # forms pagination controls become out of sync vs API goto

- src/buildFiles/templates/appcache.mustache
- src/frag/00-config.js
I did try updating to jQuery 2.1.4, but it seems to break the widget factory in jQueryMobile 1.3.x. :S
All tests are passing with the Backbone and Underscore updates.
> update to Backbone 1.2.1 and Underscore 1.8.3

- src/bic/router.js
- tests/support/server.js
- tests/support/template-data.js
- router.js : removed calls to resumeApplication
- Server.js: use appropriate headers as BMP does, so cordova can attach things, if it needs to
- template-data.js: assign same user_agent as device
ux reviewed by Ray and Rachel
> BIC-194 # interacting with some form elements (choice, camera, etc) can reload BIC

- .eslintrc
- Gruntfile.js
- karma.conf.js
- package.json
- src/bic.js
- src/bic/collection/forms.js
- src/bic/form-expressions.js
- src/bic/model/application.js
- src/bic/model/interaction.js
- src/bic/model/pending.js
- src/bic/promise-forms.js
- src/bic/router.js
- src/bic/view/form.js
- src/bic/view/form/action.js
- src/bic/view/form/controls.js
- src/bic/view/form/error-summary-list.js
- src/bic/view/interaction.js
- src/bic/view/interaction/form.js
- src/frag/10-start.frag
- tests/.eslintrc
- tests/loader.js
- tests/unit/model-interaction.js
- tests/unit/router.js
- tests/unit/view-form-action.js
- tests/unit/view-form-controls.js
- tests/unit/view-interaction-form.js
Other highlights:
- more as a proof-of-concept than anything else, extract Forms stuff out of InteractionView as its own sub-class
- `interactionModel&currentForm` is now a reference to `BMP.Forms.current` so fewer parts of the BIC actually need a direct AMD dependency upon Forms
- finally found a good home for the BIC's declaration of `BMP.Forms.getDefinition()` !!
For code review, I highly-recommend stepping through the individual commits one-by-one.
> BIC-192 # lazy-load Forms library _after_ BIC is initialised

- Gruntfile.js
- package.json
- solves issues with old ESLint in grunt plugin
> (chore) run ESLint directly, instead of via grunt

- src/bic/view/form/error-summary-list.js
- fixed reference to current form
- changed event error summary is listening to as the change:value fires before validation runs. This is only noticeable under certain circumstances.
> Feature/BIC-216 # Type Error when clicking on element in error summary

- src/bic/view/form/action.js
- src/bic/view/form/error-summary-list.js
- tests/unit/view-error-summary-list.js
- change action view to use Backbone.View#listenTo
- Track status of enhancement in ErrorSummaryView
Problem was caused by the listener for a stale view still being in the models listener hash. no idea why I used `model#on` rather than `view#listenTo` :O
> BIC-228 # Some Forms dont show client side errors

- src/bic/collection/interactions.js
- src/bic/view/form/list.js
- tests/unit/collection-interactions.js
- Fixed problem where `_.findWhere()` returns `undefined`
- Refactorred to reduce amount of times arrays are iterated over
- Removed unneeded `elements` array
Still more work can be done on refactoring functions out of the views and into the collections/models, but I thought I'd leave that for another ticket to keep this pr small.
> BIC 229 # BIC list view crashes when a Form doesnt have all Interaction actions generated

- src/bic/router.js
- src/bic/view/form/action.js
- src/bic/view/interaction.js
- tests/unit/view-interaction.js
- Interaction view now listens for `route:beforechange` event to ensure
cleanup of view happens on the old view, not the new one
- Interaction view no longer removes its element from the DOM as jqm
expects to have control over its removal
> BIC-232 # Uncaught Type Error when accessing model.attributes.currentForm

- src/frag/00-config.js
- tests/commonjs/00_appcache.js
- tests/support/index.html
- tests/support/server.js
- tests/support/template-data.js
- BIC-242: use new GZIP CDN (same as BMP) (#61, @jokeyrhyme)
- enables this and newer BIC versions on BMP 3.1.0 and newer to be used with the AppCache Fetcher
- HelpDesk: 6296-QTAZ-4747
> BIC-242 # use new GZIP CDN

- src/bic/view/form/list.js
- tests/loader.js
- tests/unit/view-form-list.js
- BIC-244: populate "list" Forms even when data has field names that don't match case (#62, @jokeyrhyme)
- note: an accompanying change to Forms library is needed for "edit" Forms, too
- HelpDesk: 4002-UDJX-6616
- dropped an Underscore dependency from one file, as we're ES5-shimming where necessary anyhow
> BIC-244 # populate "list" Forms even when data has field names that don't match case

- CHANGELOG.md
- src/bic/view/form/controls.js
- tests/unit/view-form-controls.js
-   BIC-251: submit button stops if there are form validation errors
-   really made me pine for the functional style, ES2015 and CommonJS work we've been doing more recently
-   I also made our tests use `getInvalidElements()` instead of the deprecated `getErrors()`, so that we're actually testing production code paths
> BIC-251 # submit button stops when form invalid

- CHANGELOG.md
- src/bic/promise-indexeddb.js
-   BIC-253: increase IndexedDB reliability test timeout to 5sec
-   better accommodates fluctuations in boot speed
-   HelpDesk: 1425-WDXM-4987
-   the original 1.5sec timeout was deliberately less than Mocha's default 2sec timeout
-   it seems that the browsers in which we execute tests all do so within Mocha's timeout now
> BIC-253 # increase IndexedDB test timeout to 5sec
